title: Old Dog, New Trickes
description: Stories and Tales
theme: just-the-docs

url: https://oisin.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
