# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Old Dog, New Tricks
tagline:             'writing and tales from <a href="https://twitter.com/oisin" target="_blank">@oisin</a>'
description:         'Writing and tales from <a href="https://twitter.com/oisin" target="_blank">@oisin</a>'
url:                 https://nis.io
baseurl:             ''
#paginate:            5

# About/contact
author:
  name:              Ois&iacute;n Hurley
  url:               https://twitter.com/oisin
  email:             oi.sin@nis.io

# Custom vars
version:             1.0.0
